### ISSUE TITLE
Password access control

### ISSUE THREAD

**Issue by plorch** [cleveland-metroparks/CameraTrouble#3]
* Sources
  * Hashed passwords stored somewhere
    * https://community.rstudio.com/t/password-on-a-shiny-app/27544/2
  * Older 
    *https://www.r-bloggers.com/2016/02/password-protect-shiny-apps/

**Comment by plorch** [comment]
I can use some help here.  Not sure whether using nginx for access makes more sense than the methods built into rshiny.

**Comment by smathermather** [comment]
I don't see any great benefit to leaving authentication to nginx as we are currently using it.

**Comment by plorch** [comment]
The using shinymanager seems to be a good package for this.  However, there are several limitations.
- The most secure version of this uses keyring package, which requires GUI access to set up
  - This seems like a non-starter
- Another way is to set an environment variable for the hashing passphrase
  - This seems like another installation headache as it has to be set in the app directory by creating or adding to an .Renviron file and then .gitignored
- The other method is to use a .gitignored file to bring in the passphrase used to hash passwords and decrypt them
  - Probably the way we will go
  - We already do this for database login parameters

**Comment by plorch** [comment]
This is now working.
